INSERT INTO SECTOR(ID, SECTOR_NAME, BRIEF) VALUES(101, 'Healthcare', 'Healthcare sector');
INSERT INTO SECTOR(ID, SECTOR_NAME, BRIEF) VALUES(102, 'Aviation', 'Aviation sector');
INSERT INTO SECTOR(ID, SECTOR_NAME, BRIEF) VALUES(103, 'Banking', 'Banking sector');

INSERT INTO STOCK_EXCHANGE(ID, STOCK_EXCHANGE_NAME, BRIEF, CONTACT_ADDRESS, REMARKS) VALUES(201, 'BSE', 'Bombay Stock Exchange', 'Mumbai, India', 'BSE Stock Exchange');
INSERT INTO STOCK_EXCHANGE(ID, STOCK_EXCHANGE_NAME, BRIEF, CONTACT_ADDRESS, REMARKS) VALUES(202, 'NSE', 'National Stock Exchange', 'Mumbai, India', 'NSE Stock Exchange');