INSERT INTO SECTOR(ID, SECTOR_NAME, BRIEF) VALUES(101, 'Healthcare', 'Healthcare sector');
INSERT INTO SECTOR(ID, SECTOR_NAME, BRIEF) VALUES(102, 'Aviation', 'Aviation sector');
INSERT INTO SECTOR(ID, SECTOR_NAME, BRIEF) VALUES(103, 'Banking', 'Banking sector');
INSERT INTO SECTOR(ID, SECTOR_NAME, BRIEF) VALUES(104, 'IT', 'IT sector');

INSERT INTO STOCK_EXCHANGE(ID, STOCK_EXCHANGE_NAME, BRIEF, CONTACT_ADDRESS, REMARKS) VALUES(201, 'BSE', 'Bombay Stock Exchange', 'Mumbai, India', 'BSE Stock Exchange');
INSERT INTO STOCK_EXCHANGE(ID, STOCK_EXCHANGE_NAME, BRIEF, CONTACT_ADDRESS, REMARKS) VALUES(202, 'NSE', 'National Stock Exchange', 'Mumbai, India', 'NSE Stock Exchange');

INSERT INTO COMPANY(ID, COMPANY_NAME, TURNOVER, CEO, BOARD_OF_DIRECTORS, LISTED_IN_STOCK_EXCHANGES, SECTOR_ID, BRIEF, DEACTIVATED) VALUES(301, 'Amazon', 400000, 'Jeff Bezos', 'Andy Jassy, Keith Alexander', true, 104, 'Amazon Shopping', false);
INSERT INTO COMPANY(ID, COMPANY_NAME, TURNOVER, CEO, BOARD_OF_DIRECTORS, LISTED_IN_STOCK_EXCHANGES, SECTOR_ID, BRIEF, DEACTIVATED) VALUES(500112, 'State Bank Of India', 500000, ' Dinesh Kumar Khara', 'Sanjeev Nautiyal, Rana Ashutosh Kumar', true, 103, 'SBI Banking', false);
INSERT INTO COMPANY(ID, COMPANY_NAME, TURNOVER, CEO, BOARD_OF_DIRECTORS, LISTED_IN_STOCK_EXCHANGES, SECTOR_ID, BRIEF, DEACTIVATED) VALUES(302, 'Google', 500000, 'Sundar Pichai', 'Andy Jassy, Keith Alexander', true, 104, 'Google', false);
INSERT INTO COMPANY(ID, COMPANY_NAME, TURNOVER, CEO, BOARD_OF_DIRECTORS, LISTED_IN_STOCK_EXCHANGES, SECTOR_ID, BRIEF, DEACTIVATED) VALUES(303, 'Goldman Sachs', 500000, 'David M. Solomon', 'Andy Jassy, Keith Alexander', true, 104, 'Google', false);
INSERT INTO COMPANY(ID, COMPANY_NAME, TURNOVER, CEO, BOARD_OF_DIRECTORS, LISTED_IN_STOCK_EXCHANGES, SECTOR_ID, BRIEF, DEACTIVATED) VALUES(304, 'General Electric', 500000, 'Alok Nanda', 'Andy Jassy, Keith Alexander', true, 104, 'Google', false);
INSERT INTO COMPANY(ID, COMPANY_NAME, TURNOVER, CEO, BOARD_OF_DIRECTORS, LISTED_IN_STOCK_EXCHANGES, SECTOR_ID, BRIEF, DEACTIVATED) VALUES(305, 'Geekay Exim', 500000, 'Ninad Kothari', 'Andy Jassy, Keith Alexander', true, 104, 'Google', false);
INSERT INTO COMPANY(ID, COMPANY_NAME, TURNOVER, CEO, BOARD_OF_DIRECTORS, LISTED_IN_STOCK_EXCHANGES, SECTOR_ID, BRIEF, DEACTIVATED) VALUES(306, 'Geekay Imaging', 500000, 'Govind Deshpande', 'Andy Jassy, Keith Alexander', true, 104, 'Google', false);